"""empty message

Revision ID: beda3de0d754
Revises: da997871dc6e
Create Date: 2020-03-03 12:04:11.019808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beda3de0d754'
down_revision = 'da997871dc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housing', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('housing', sa.Column('locality_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'housing', 'localities', ['locality_id'], ['id'])
    op.create_foreign_key(None, 'housing', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'housing', type_='foreignkey')
    op.drop_constraint(None, 'housing', type_='foreignkey')
    op.drop_column('housing', 'locality_id')
    op.drop_column('housing', 'category_id')
    # ### end Alembic commands ###
