"""empty message

Revision ID: d316ad2e3926
Revises: 86d3bcb73a07
Create Date: 2020-03-04 10:21:14.554004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd316ad2e3926'
down_revision = '86d3bcb73a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('housing_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'room_types', 'housing', ['housing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_types', type_='foreignkey')
    op.drop_column('room_types', 'housing_id')
    # ### end Alembic commands ###
